export default {
  disciplines: [
    'Other',
    'Accounting/Finance',
    'Acoustics',
    'Agriculture',
    'Allied Health',
    'Animal Science',
    'Anthropology',
    'Archaeology',
    'Architecture',
    'Area Studies',
    'Art History',
    'Arts',
    'Astronomy',
    'Biology',
    'Biomedical Engineering',
    'Business',
    'Chemistry',
    'Communications',
    'Computer Science',
    'Criminal Justice',
    'Criminology',
    'Crop Sciences',
    'Culinary Arts',
    'Dance',
    'Demography',
    'Dental Sciences',
    'Design',
    'Drama/Theater Arts',
    'Economics',
    'Education',
    'Engineering',
    'Environmental Sciences',
    'Fashion',
    'Film/Cinema Studies',
    'Fine Arts',
    'Fisheries',
    'Forestry',
    'Gender Studies',
    'Geography',
    'Geology',
    'History',
    'Information Sciences/Systems',
    'International Relations',
    'Journalism',
    'Language',
    'Language Teaching',
    'Law',
    'Library Science',
    'Linguistics',
    'Literature',
    'Marketing',
    'Materials Science',
    'Mathematics',
    'Medical Sciences',
    'Meteorology',
    'Museum Studies',
    'Music',
    'Music Studies',
    'Neuroscience',
    'Nursing',
    'Nutrition',
    'Oceanography',
    'Paleontology',
    'Philosophy',
    'Physics',
    'Political Science',
    'Psychology',
    'Public Policy',
    'Religious Studies',
    'Social Work',
    'Sociology',
    'Telecommunications',
    'Theology/Religion',
    'Travel/Tourism',
    'Urban Planning',
    'Urban Studies',
    'Veterinary Medicine',
    'Writing'
  ]
}
